//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bloodResource
    {
        public int quantity { get; set; }
        public int idCenter { get; set; }
        public int idBlood { get; set; }
    
        public virtual Blood Blood { get; set; }
        public virtual donationCenter donationCenter { get; set; }
    }
}
