//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public int idDonor { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public System.DateTime birthDate { get; set; }
        public string homeTown { get; set; }
        public string email { get; set; }
        public string phoneNumber { get; set; }
        public string RH { get; set; }
        public Nullable<int> idCenter { get; set; }
    
        public virtual donationCenter donationCenter { get; set; }
    }
}
