//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int idPatient { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string group { get; set; }
        public string RH { get; set; }
        public Nullable<int> idMedic { get; set; }
    
        public virtual Medic Medic { get; set; }
    }
}
